# Generated by Django 5.2.14 on 2026-05-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('rubric', models.TextField(help_text='AI-generated relevance rubric — what the problem is, who has it, intent signals, and non-examples.')),
                ('keywords', models.JSONField(default=list, help_text='List of search queries/keywords for Reddit/X.')),
                ('score_threshold', models.IntegerField(default=60, help_text='Minimum AI score (0-100) to keep an item.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('reddit', 'Reddit'), ('x', 'X (Twitter)')], max_length=20)),
                ('source_url', models.URLField(max_length=1000)),
                ('author', models.CharField(max_length=300)),
                ('text_snippet', models.TextField()),
                ('dedup_key', models.CharField(max_length=600, unique=True)),
                ('score', models.IntegerField()),
                ('why_relevant', models.TextField()),
                ('what_theyre_asking', models.TextField()),
                ('suggested_angle', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('ignored', 'Ignored'), ('sent', 'Sent in digest')], default='new', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.topic')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
