# Generated by Django 5.2.14 on 2026-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_interval_hours', models.IntegerField(default=6, help_text='How often (in hours) to fetch and score new posts.')),
                ('poll_enabled', models.BooleanField(default=True)),
                ('digest_hour', models.IntegerField(default=8, help_text='Hour of day (UTC, 0–23) to send the daily digest.')),
                ('digest_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schedule config',
            },
        ),
    ]
