# Generated by Django 5.2.14 on 2026-05-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scheduleconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleConfig',
        ),
    ]
