# Generated by Django 5.2.14 on 2026-05-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_scheduleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_to_email', models.EmailField(blank=True, default='', help_text='Email address to receive the daily digest.', max_length=254)),
                ('slack_webhook_url', models.CharField(blank=True, default='', help_text='Slack incoming webhook URL.', max_length=500)),
            ],
            options={
                'verbose_name': 'Notification settings',
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='topic',
            name='rubric',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='score_threshold',
            field=models.IntegerField(default=60),
        ),
    ]
