# Generated by Django 5.0.7 on 2026-06-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='matcheditem',
            name='platform',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('x', 'X (Twitter)'), ('web', 'Web')], max_length=20),
        ),
    ]
